import { useInterviewStore } from '../../stores/interviewStore'

/** Shows which engine is driving the interview: the LLM model or the offline engine. */
export function EngineBadge() {
  const engine = useInterviewStore((s) => s.engine)
  const engineModel = useInterviewStore((s) => s.engineModel)

  const llm = engine === 'llm'
  const label = llm ? (engineModel ? `LLM · ${engineModel}` : 'LLM') : 'Offline engine'
  const title = llm
    ? `Interview generated by ${engineModel ?? 'the configured model'}`
    : 'Interview driven by the deterministic offline engine'

  return (
    <span
      aria-label="Engine status"
      title={title}
      className={`inline-flex items-center gap-1.5 font-mono text-xs uppercase tracking-widest ${
        llm ? 'text-accent' : 'text-text-dim/70'
      }`}
    >
      <span
        aria-hidden="true"
        className={`h-1.5 w-1.5 rounded-full ${llm ? 'bg-accent' : 'bg-text-dim/50'}`}
      />
      {label}
    </span>
  )
}
